// python-learning-hub/advanced_lessons.js

(function () {
  if (typeof lessons === "undefined") {
    throw new Error("advanced_lessons.js must be loaded after lessons.js");
  }

  function makeLesson(spec) {
    return {
      id: spec.id,
      level: spec.level,
      title: spec.title,
      description: `### ${spec.heading}\n\n${spec.concept}\n\n#### 🧭 独立开发能力\n${spec.ability}\n\n#### 📝 示例方向\n\`\`\`python\n${spec.example}\n\`\`\``,
      task: spec.task,
      hint: spec.hint,
      defaultCode: spec.defaultCode,
      solution: spec.solution,
      validate: async (code, stdout, globals, pyodide) => {
        if (spec.requireCode) {
          for (const req of spec.requireCode) {
            const token = Array.isArray(req) ? req[0] : req;
            const message = Array.isArray(req) ? req[1] : `本关需要在代码中使用 ${token}。`;
            if (!code.includes(token)) return { success: false, message };
          }
        }

        if (spec.requiredNames) {
          for (const name of spec.requiredNames) {
            if (!globals.has(name)) return { success: false, message: `未检测到 ${name}。` };
          }
        }

        if (spec.assertCode) {
          try {
            await pyodide.runPythonAsync(spec.assertCode);
          } catch (err) {
            return { success: false, message: spec.failPrefix + err.message };
          }
        }

        return { success: true, message: spec.success };
      }
    };
  }

  const advancedLessons = [
    makeLesson({
      id: 31,
      level: 6,
      title: "31. 项目蓝图 (Project Structure)",
      heading: "从一段脚本走向一个项目",
      concept: "独立开发的第一步不是写很多代码，而是先把项目拆成入口文件、功能模块、数据文件和说明文档。清晰的结构会让后续调试、扩展和交付都轻松很多。",
      ability: "能为一个小项目设计最基础的文件结构，并知道哪个文件负责启动程序。",
      example: "project_files = {\"main.py\": \"启动入口\", \"utils.py\": \"工具函数\"}\nentry_file = \"main.py\"",
      task: "请创建字典 `project_files`，包含 `main.py`、`utils.py`、`data.json`、`README.md` 四个键，并分别描述它们的职责。再创建变量 `entry_file`，值为 `\"main.py\"`，以及变量 `module_count`，值为文件数量。",
      hint: "project_files 是字典，module_count 可以用 len(project_files) 得到。",
      defaultCode: "# 设计一个小项目的文件结构\nproject_files = {}\nentry_file = \"\"\nmodule_count = 0\n",
      solution: "project_files = {\n    \"main.py\": \"程序入口\",\n    \"utils.py\": \"工具函数\",\n    \"data.json\": \"数据存储\",\n    \"README.md\": \"项目说明\"\n}\nentry_file = \"main.py\"\nmodule_count = len(project_files)",
      requiredNames: ["project_files", "entry_file", "module_count"],
      assertCode: `assert set(project_files.keys()) == {"main.py", "utils.py", "data.json", "README.md"}\nassert entry_file == "main.py"\nassert module_count == 4`,
      failPrefix: "项目结构检查失败：",
      success: "很好！你已经开始用项目结构来思考程序，而不是只写孤立脚本。"
    }),
    makeLesson({
      id: 32,
      level: 6,
      title: "32. 拆出工具模块 (Create & Import Module)",
      heading: "把可复用函数放进模块",
      concept: "当代码变多时，把工具函数放进单独的 `.py` 文件，再从主程序导入，是最常见的组织方式。浏览器里的 Pyodide 也支持创建临时 Python 文件并导入。",
      ability: "能创建一个简单模块文件，并在主代码中导入调用。",
      example: "with open(\"math_tools.py\", \"w\") as f:\n    f.write(\"def add(a, b):\\n    return a + b\\n\")\nimport math_tools",
      task: "请创建文件 `math_tools.py`，里面定义函数 `add(a, b)` 返回两数之和。然后导入 `math_tools`，调用 `math_tools.add(12, 30)`，把结果存入 `module_result`。",
      hint: "可以用 with open 写入模块文本。写完后 import math_tools，再调用 add。",
      defaultCode: "# 创建并导入自己的工具模块\n",
      solution: "with open(\"math_tools.py\", \"w\", encoding=\"utf-8\") as f:\n    f.write(\"def add(a, b):\\n    return a + b\\n\")\n\nimport math_tools\nmodule_result = math_tools.add(12, 30)",
      requireCode: ["with open", "import math_tools"],
      requiredNames: ["module_result"],
      assertCode: `assert module_result == 42\nimport math_tools\nassert math_tools.add(1, 2) == 3`,
      failPrefix: "模块导入检查失败：",
      success: "通关！你已经会把函数拆到独立模块里复用了。"
    }),
    makeLesson({
      id: 33,
      level: 6,
      title: "33. 程序入口保护 (__main__ Guard)",
      heading: "让文件既能运行，也能被导入",
      concept: "`if __name__ == \"__main__\":` 是 Python 项目的常见入口保护。它能让一个文件被直接运行时执行主流程，被导入时只提供函数和类。",
      ability: "能写出带 main() 函数和入口保护的脚本骨架。",
      example: "def main():\n    return \"ready\"\n\nif __name__ == \"__main__\":\n    main()",
      task: "请定义函数 `main()`，返回字符串 `\"app started\"`。再创建字符串变量 `entry_guard_code`，内容必须包含 `if __name__ == \"__main__\":` 和 `main()`，表示标准入口保护代码。",
      hint: "函数是真实定义，入口保护这次用字符串保存，方便在浏览器里验证结构。",
      defaultCode: "# 编写 main 函数和入口保护代码文本\n",
      solution: "def main():\n    return \"app started\"\n\nentry_guard_code = 'if __name__ == \"__main__\":\\n    main()'",
      requiredNames: ["main", "entry_guard_code"],
      assertCode: `assert main() == "app started"\nassert 'if __name__ == "__main__":' in entry_guard_code\nassert "main()" in entry_guard_code`,
      failPrefix: "入口保护检查失败：",
      success: "很好！你已经理解了可运行脚本的标准入口写法。"
    }),
    makeLesson({
      id: 34,
      level: 6,
      title: "34. 日志记录 (Logging)",
      heading: "用日志替代到处 print",
      concept: "独立开发时，日志比 print 更适合记录程序运行状态。日志可以区分 INFO、WARNING、ERROR 等级，也更容易在项目里统一管理。",
      ability: "能配置一个基础 logger，并输出一条可追踪的状态信息。",
      example: "import logging\nlogging.basicConfig(level=logging.INFO)\nlogging.info(\"app started\")",
      task: "请导入 `logging`，配置基础日志等级为 `logging.INFO`。创建变量 `log_message = \"user loaded\"`，并调用 `logging.info(log_message)`。",
      hint: "使用 logging.basicConfig(level=logging.INFO)。",
      defaultCode: "# 使用 logging 记录程序状态\n",
      solution: "import logging\nlogging.basicConfig(level=logging.INFO)\nlog_message = \"user loaded\"\nlogging.info(log_message)",
      requireCode: ["import logging", "logging.info"],
      requiredNames: ["log_message"],
      assertCode: `assert log_message == "user loaded"`,
      failPrefix: "日志检查失败：",
      success: "通关！你已经开始使用项目级日志思维。"
    }),
    makeLesson({
      id: 35,
      level: 6,
      title: "35. 断言式调试 (Assertions)",
      heading: "把假设写进代码里",
      concept: "调试不是瞎猜。你可以用断言表达“这里必须成立”的条件，一旦条件不满足，程序会立刻告诉你哪里出了问题。",
      ability: "能写出带断言保护的小函数，提前发现错误输入。",
      example: "def half(n):\n    assert n >= 0\n    return n / 2",
      task: "请定义函数 `normalize_score(score)`：使用 `assert` 确保分数在 0 到 100 之间，然后返回 `score / 100`。",
      hint: "assert 0 <= score <= 100，然后 return score / 100。",
      defaultCode: "def normalize_score(score):\n    # 使用 assert 检查范围\n    pass\n",
      solution: "def normalize_score(score):\n    assert 0 <= score <= 100\n    return score / 100",
      requireCode: ["assert"],
      requiredNames: ["normalize_score"],
      assertCode: `assert normalize_score(80) == 0.8\ntry:\n    normalize_score(120)\n    raise AssertionError("超出范围时应触发 AssertionError")\nexcept AssertionError:\n    pass`,
      failPrefix: "断言调试检查失败：",
      success: "不错！你会把关键假设写进函数里了。"
    }),
    makeLesson({
      id: 36,
      level: 6,
      title: "36. 读懂报错 (Traceback Parsing)",
      heading: "从报错里提取线索",
      concept: "独立开发离不开读报错。最关键的信息通常是异常类型、文件行号和最后一行错误原因。先读懂它，再动手修。",
      ability: "能从一段简化的报错文本中提取异常类型和行号。",
      example: "error_text = \"line 7: ValueError: bad value\"\nexception_type = \"ValueError\"",
      task: "已给出字符串 `error_text = \"File app.py, line 7, ValueError: bad value\"`。请提取异常类型到 `exception_type`，提取行号整数到 `line_number`。",
      hint: "可以用 split 拆分文本。异常类型是 `ValueError`，行号是 7。",
      defaultCode: "error_text = \"File app.py, line 7, ValueError: bad value\"\n# 提取 exception_type 和 line_number\n",
      solution: "error_text = \"File app.py, line 7, ValueError: bad value\"\nparts = error_text.split(\",\")\nline_number = int(parts[1].strip().split()[1])\nexception_type = parts[2].strip().split(\":\")[0]",
      requiredNames: ["exception_type", "line_number"],
      assertCode: `assert exception_type == "ValueError"\nassert line_number == 7`,
      failPrefix: "报错解析检查失败：",
      success: "很好！你开始会从报错信息里抓重点了。"
    }),
    makeLesson({
      id: 37,
      level: 6,
      title: "37. 类型提示 (Type Hints)",
      heading: "让函数接口更清楚",
      concept: "类型提示不会强制改变 Python 的运行方式，但它能让函数的输入输出一眼可见，也能帮助编辑器和队友理解代码。",
      ability: "能为函数参数和返回值添加基础类型提示。",
      example: "def greet(name: str) -> str:\n    return f\"Hi {name}\"",
      task: "请定义函数 `format_user(name: str, age: int) -> str`，返回格式 `\"Alice (20)\"`。",
      hint: "函数签名里写 `name: str, age: int`，返回值提示写 `-> str`。",
      defaultCode: "# 编写带类型提示的 format_user 函数\n",
      solution: "def format_user(name: str, age: int) -> str:\n    return f\"{name} ({age})\"",
      requireCode: ["-> str", ": int"],
      requiredNames: ["format_user"],
      assertCode: `assert format_user("Alice", 20) == "Alice (20)"\nassert format_user.__annotations__["name"] is str\nassert format_user.__annotations__["age"] is int\nassert format_user.__annotations__["return"] is str`,
      failPrefix: "类型提示检查失败：",
      success: "通关！清晰的函数接口是工程代码的开端。"
    }),
    makeLesson({
      id: 38,
      level: 6,
      title: "38. 数据类 (Dataclass)",
      heading: "用 dataclass 表达数据模型",
      concept: "`dataclass` 可以快速声明主要用于存储数据的类，自动生成构造方法和可读的对象表示，非常适合项目里的配置、记录和模型。",
      ability: "能用 dataclass 创建一个简单的数据模型。",
      example: "from dataclasses import dataclass\n@dataclass\nclass User:\n    name: str",
      task: "请导入 `dataclass`，定义数据类 `TaskItem`，包含 `title: str` 和 `done: bool = False`。创建实例 `first_task = TaskItem(\"learn\")`。",
      hint: "在类上方写 @dataclass，字段直接写类型提示。",
      defaultCode: "# 使用 dataclass 定义 TaskItem\n",
      solution: "from dataclasses import dataclass\n\n@dataclass\nclass TaskItem:\n    title: str\n    done: bool = False\n\nfirst_task = TaskItem(\"learn\")",
      requireCode: ["@dataclass"],
      requiredNames: ["TaskItem", "first_task"],
      assertCode: `assert first_task.title == "learn"\nassert first_task.done is False\nassert TaskItem("ship", True).done is True`,
      failPrefix: "dataclass 检查失败：",
      success: "很好！你已经能用数据模型来表达项目里的实体了。"
    }),
    makeLesson({
      id: 39,
      level: 6,
      title: "39. 配置管理 (Config)",
      heading: "不要把配置散落在代码里",
      concept: "项目常有调试开关、版本号、文件路径等配置。把它们集中管理，程序会更容易修改和部署。",
      ability: "能使用字典集中保存配置，并派生出运行模式。",
      example: "APP_CONFIG = {\"debug\": True}\nmode = \"dev\" if APP_CONFIG[\"debug\"] else \"prod\"",
      task: "请创建字典 `APP_CONFIG`，包含 `debug=True`、`version=\"1.0\"`、`data_file=\"data.json\"`。再创建 `run_mode`，如果 debug 为真则为 `\"development\"`，否则为 `\"production\"`。",
      hint: "run_mode 可以用三元表达式完成。",
      defaultCode: "# 创建项目配置 APP_CONFIG 和运行模式 run_mode\n",
      solution: "APP_CONFIG = {\n    \"debug\": True,\n    \"version\": \"1.0\",\n    \"data_file\": \"data.json\"\n}\nrun_mode = \"development\" if APP_CONFIG[\"debug\"] else \"production\"",
      requiredNames: ["APP_CONFIG", "run_mode"],
      assertCode: `assert APP_CONFIG["debug"] is True\nassert APP_CONFIG["version"] == "1.0"\nassert APP_CONFIG["data_file"] == "data.json"\nassert run_mode == "development"`,
      failPrefix: "配置管理检查失败：",
      success: "通关！配置集中后，项目会更容易维护。"
    }),
    makeLesson({
      id: 40,
      level: 6,
      title: "40. 工程小结：可维护脚本",
      heading: "把工程习惯揉进一个脚本",
      concept: "一个像样的小脚本通常会有配置、函数、入口、日志或状态信息。它不一定复杂，但结构要清楚。",
      ability: "能写出带配置、函数和 main 入口的迷你工程脚本。",
      example: "CONFIG = {\"prefix\": \"Hi\"}\ndef main():\n    return CONFIG[\"prefix\"]",
      task: "请创建 `CONFIG = {\"prefix\": \"Hello\"}`，定义函数 `build_message(name)` 返回 `\"Hello, {name}\"`，再定义 `main()` 返回 `build_message(\"YYS\")`，最后把 `main()` 的结果存入 `app_output`。",
      hint: "main 里调用 build_message，app_output = main()。",
      defaultCode: "# 写一个有配置、函数和 main 的小脚本\n",
      solution: "CONFIG = {\"prefix\": \"Hello\"}\n\ndef build_message(name):\n    return f\"{CONFIG['prefix']}, {name}\"\n\ndef main():\n    return build_message(\"YYS\")\n\napp_output = main()",
      requiredNames: ["CONFIG", "build_message", "main", "app_output"],
      assertCode: `assert build_message("Alice") == "Hello, Alice"\nassert main() == "Hello, YYS"\nassert app_output == "Hello, YYS"`,
      failPrefix: "可维护脚本检查失败：",
      success: "Level 6 通关！你已经具备了从脚本走向项目的基本工程意识。"
    }),
    makeLesson({
      id: 41,
      level: 7,
      title: "41. CSV 读写 (CSV Files)",
      heading: "处理表格文本数据",
      concept: "CSV 是最常见的数据交换格式之一。很多报表、后台导出、数据集都可以先用 CSV 处理。",
      ability: "能写入并读回 CSV 数据。",
      example: "import csv\nwith open(\"data.csv\", \"w\", newline=\"\") as f:\n    csv.writer(f).writerow([\"name\", \"score\"])",
      task: "请使用 `csv` 模块创建 `scores.csv`，写入表头 `name,score` 和两行数据 `Alice,90`、`Bob,80`。再读回文件，把数据行数量存入 `row_count`。",
      hint: "写入时使用 newline=\"\"；读回时可以 list(csv.DictReader(f))。",
      defaultCode: "# 使用 csv 写入并读回 scores.csv\n",
      solution: "import csv\n\nwith open(\"scores.csv\", \"w\", newline=\"\", encoding=\"utf-8\") as f:\n    writer = csv.writer(f)\n    writer.writerow([\"name\", \"score\"])\n    writer.writerow([\"Alice\", 90])\n    writer.writerow([\"Bob\", 80])\n\nwith open(\"scores.csv\", \"r\", encoding=\"utf-8\") as f:\n    rows = list(csv.DictReader(f))\nrow_count = len(rows)",
      requireCode: ["import csv", "DictReader"],
      requiredNames: ["row_count"],
      assertCode: `assert row_count == 2\nimport csv\nwith open("scores.csv", encoding="utf-8") as f:\n    rows = list(csv.DictReader(f))\nassert rows[0]["name"] == "Alice"\nassert rows[1]["score"] == "80"`,
      failPrefix: "CSV 读写检查失败：",
      success: "通关！你可以开始处理真实世界里的表格数据了。"
    }),
    makeLesson({
      id: 42,
      level: 7,
      title: "42. 数据过滤 (Filter Rows)",
      heading: "从数据里筛出有用信息",
      concept: "独立开发常常要从一批数据中筛选出符合条件的记录，比如高分学生、过期订单、异常日志。",
      ability: "能用列表推导式过滤字典列表。",
      example: "passed = [row for row in rows if row[\"score\"] >= 60]",
      task: "已给出 `records` 列表。请筛选出 `score >= 80` 的记录，存入 `top_records`；再把这些人的名字提取到 `top_names`。",
      hint: "top_records 用列表推导式，top_names 再从 top_records 中提取 name。",
      defaultCode: "records = [{\"name\": \"Alice\", \"score\": 90}, {\"name\": \"Bob\", \"score\": 75}, {\"name\": \"Cindy\", \"score\": 88}]\n# 筛选高分记录\n",
      solution: "records = [{\"name\": \"Alice\", \"score\": 90}, {\"name\": \"Bob\", \"score\": 75}, {\"name\": \"Cindy\", \"score\": 88}]\ntop_records = [row for row in records if row[\"score\"] >= 80]\ntop_names = [row[\"name\"] for row in top_records]",
      requiredNames: ["top_records", "top_names"],
      assertCode: `assert [row["name"] for row in top_records] == ["Alice", "Cindy"]\nassert top_names == ["Alice", "Cindy"]`,
      failPrefix: "数据过滤检查失败：",
      success: "很好！筛选是所有数据工具的基本功。"
    }),
    makeLesson({
      id: 43,
      level: 7,
      title: "43. JSON Lines 日志 (JSONL)",
      heading: "一行一条记录",
      concept: "JSON Lines 常用于日志和大批量数据，每一行都是一个独立 JSON 对象，适合逐行读取和追加写入。",
      ability: "能写入并逐行读取 JSONL 数据。",
      example: "for line in f:\n    item = json.loads(line)",
      task: "请创建 `events.jsonl`，写入两条事件：`{\"type\":\"open\",\"user\":\"A\"}` 和 `{\"type\":\"click\",\"user\":\"A\"}`。再逐行读回，统计事件数量到 `event_count`，把所有 type 存入 `event_types`。",
      hint: "每次 json.dumps(obj) 后加一个换行。",
      defaultCode: "# 写入并读取 JSON Lines\n",
      solution: "import json\n\nevents = [{\"type\": \"open\", \"user\": \"A\"}, {\"type\": \"click\", \"user\": \"A\"}]\nwith open(\"events.jsonl\", \"w\", encoding=\"utf-8\") as f:\n    for event in events:\n        f.write(json.dumps(event) + \"\\n\")\n\nloaded_events = []\nwith open(\"events.jsonl\", \"r\", encoding=\"utf-8\") as f:\n    for line in f:\n        loaded_events.append(json.loads(line))\nevent_count = len(loaded_events)\nevent_types = [event[\"type\"] for event in loaded_events]",
      requireCode: ["json.dumps", "json.loads"],
      requiredNames: ["event_count", "event_types"],
      assertCode: `assert event_count == 2\nassert event_types == ["open", "click"]`,
      failPrefix: "JSONL 检查失败：",
      success: "通关！你已经掌握了日志型数据的常见格式。"
    }),
    makeLesson({
      id: 44,
      level: 7,
      title: "44. 批量文件扫描 (Pathlib Glob)",
      heading: "让程序自己找文件",
      concept: "很多工具都需要扫描目录，比如找出所有图片、所有日志、所有 CSV。`Path.glob()` 是跨平台的文件匹配方法。",
      ability: "能创建目录并用 glob 批量查找文件。",
      example: "from pathlib import Path\nfiles = list(Path(\"data\").glob(\"*.txt\"))",
      task: "请创建目录 `inbox`，在其中创建 `a.txt`、`b.txt`、`image.png` 三个文件。使用 `Path(\"inbox\").glob(\"*.txt\")` 找出所有 txt 文件，将文件名排序后存入 `txt_files`。",
      hint: "txt_files 应该是 ['a.txt', 'b.txt']。",
      defaultCode: "# 使用 pathlib 扫描 txt 文件\n",
      solution: "from pathlib import Path\n\ninbox = Path(\"inbox\")\ninbox.mkdir(exist_ok=True)\nfor name in [\"a.txt\", \"b.txt\", \"image.png\"]:\n    (inbox / name).write_text(\"demo\", encoding=\"utf-8\")\n\ntxt_files = sorted(path.name for path in inbox.glob(\"*.txt\"))",
      requireCode: ["Path", "glob"],
      requiredNames: ["txt_files"],
      assertCode: `assert txt_files == ["a.txt", "b.txt"]`,
      failPrefix: "文件扫描检查失败：",
      success: "很好！你已经能让程序自动发现目标文件了。"
    }),
    makeLesson({
      id: 45,
      level: 7,
      title: "45. 批量重命名计划 (Rename Plan)",
      heading: "先规划，再改文件",
      concept: "真实批量重命名前，最好先生成计划并检查，避免误操作。这个关卡练习生成重命名映射。",
      ability: "能根据文件列表生成可审查的重命名计划。",
      example: "rename_plan = {old: new for old, new in pairs}",
      task: "给定 `files = [\"img_1.png\", \"img_2.png\", \"note.txt\"]`，请为 png 文件生成字典 `rename_plan`，把它们映射为 `photo_1.png`、`photo_2.png`，忽略 txt 文件。",
      hint: "遍历 files，判断 name.endswith('.png')。",
      defaultCode: "files = [\"img_1.png\", \"img_2.png\", \"note.txt\"]\nrename_plan = {}\n# 生成重命名计划\n",
      solution: "files = [\"img_1.png\", \"img_2.png\", \"note.txt\"]\nrename_plan = {}\nfor name in files:\n    if name.endswith(\".png\"):\n        new_name = name.replace(\"img_\", \"photo_\")\n        rename_plan[name] = new_name",
      requiredNames: ["rename_plan"],
      assertCode: `assert rename_plan == {"img_1.png": "photo_1.png", "img_2.png": "photo_2.png"}`,
      failPrefix: "重命名计划检查失败：",
      success: "通关！先生成计划，是写安全工具的好习惯。"
    }),
    makeLesson({
      id: 46,
      level: 7,
      title: "46. 生成文本报告 (Reports)",
      heading: "把数据变成可读结果",
      concept: "开发工具不只是处理数据，还要把结果交给人看。报告可以是纯文本、Markdown、HTML 或表格。",
      ability: "能根据数据生成 Markdown 风格报告。",
      example: "report = \"# Report\\nTotal: 3\"",
      task: "给定 `summary = {\"total\": 3, \"passed\": 2}`，请生成字符串 `report`，包含标题 `# 学习报告`，以及 `总数: 3`、`通过: 2` 两行。",
      hint: "可以使用 f-string 和换行符。",
      defaultCode: "summary = {\"total\": 3, \"passed\": 2}\n# 生成 report 字符串\n",
      solution: "summary = {\"total\": 3, \"passed\": 2}\nreport = f\"# 学习报告\\n总数: {summary['total']}\\n通过: {summary['passed']}\"",
      requiredNames: ["report"],
      assertCode: `assert "# 学习报告" in report\nassert "总数: 3" in report\nassert "通过: 2" in report`,
      failPrefix: "报告生成检查失败：",
      success: "很好！工具输出变得更像可交付成果了。"
    }),
    makeLesson({
      id: 47,
      level: 7,
      title: "47. 分组统计 (Group By)",
      heading: "按类别汇总数据",
      concept: "销售额按月份统计、任务按状态统计、日志按等级统计，都是分组统计问题。",
      ability: "能用字典累加实现 group by。",
      example: "totals = {}\nfor row in rows:\n    totals[row[\"type\"]] = totals.get(row[\"type\"], 0) + row[\"amount\"]",
      task: "给定订单列表 `orders`，请按 `category` 汇总 `amount`，结果存入字典 `category_totals`。",
      hint: "使用 get 默认值 0 累加。",
      defaultCode: "orders = [{\"category\": \"book\", \"amount\": 30}, {\"category\": \"food\", \"amount\": 20}, {\"category\": \"book\", \"amount\": 45}]\ncategory_totals = {}\n# 按类别汇总金额\n",
      solution: "orders = [{\"category\": \"book\", \"amount\": 30}, {\"category\": \"food\", \"amount\": 20}, {\"category\": \"book\", \"amount\": 45}]\ncategory_totals = {}\nfor order in orders:\n    category = order[\"category\"]\n    category_totals[category] = category_totals.get(category, 0) + order[\"amount\"]",
      requiredNames: ["category_totals"],
      assertCode: `assert category_totals == {"book": 75, "food": 20}`,
      failPrefix: "分组统计检查失败：",
      success: "通关！这是数据分析和报表工具的核心套路。"
    }),
    makeLesson({
      id: 48,
      level: 7,
      title: "48. 日期窗口筛选 (Date Windows)",
      heading: "按时间范围处理数据",
      concept: "很多业务逻辑都和时间窗口有关，比如最近 7 天订单、本月账单、过期提醒。",
      ability: "能解析日期并筛选指定时间范围内的数据。",
      example: "dt = datetime.strptime(row[\"date\"], \"%Y-%m-%d\")",
      task: "给定 `logs` 和起止日期，请筛选出日期在 `2026-05-01` 到 `2026-05-31` 之间的记录，存入 `may_logs`，并把数量存入 `may_count`。",
      hint: "用 datetime.strptime 解析字符串后比较。",
      defaultCode: "logs = [{\"date\": \"2026-04-30\"}, {\"date\": \"2026-05-10\"}, {\"date\": \"2026-06-01\"}]\n# 筛选 2026 年 5 月记录\n",
      solution: "from datetime import datetime\n\nlogs = [{\"date\": \"2026-04-30\"}, {\"date\": \"2026-05-10\"}, {\"date\": \"2026-06-01\"}]\nstart = datetime.strptime(\"2026-05-01\", \"%Y-%m-%d\")\nend = datetime.strptime(\"2026-05-31\", \"%Y-%m-%d\")\nmay_logs = []\nfor log in logs:\n    dt = datetime.strptime(log[\"date\"], \"%Y-%m-%d\")\n    if start <= dt <= end:\n        may_logs.append(log)\nmay_count = len(may_logs)",
      requireCode: ["strptime"],
      requiredNames: ["may_logs", "may_count"],
      assertCode: `assert may_count == 1\nassert may_logs[0]["date"] == "2026-05-10"`,
      failPrefix: "日期筛选检查失败：",
      success: "很好！你能处理有时间边界的数据了。"
    }),
    makeLesson({
      id: 49,
      level: 7,
      title: "49. 文件备份 (Copy Backup)",
      heading: "保留一份安全副本",
      concept: "写会修改文件的工具前，先备份是一种成熟习惯。`shutil.copyfile` 可以复制文件。",
      ability: "能创建文件并生成备份副本。",
      example: "import shutil\nshutil.copyfile(\"data.txt\", \"data.bak\")",
      task: "请创建文件 `profile.txt`，内容为 `name=YYS`。然后使用 `shutil.copyfile` 复制为 `profile.bak`，并读取备份内容到 `backup_text`。",
      hint: "先写文件，再 copyfile，最后 read。",
      defaultCode: "# 创建 profile.txt 并复制备份\n",
      solution: "import shutil\n\nwith open(\"profile.txt\", \"w\", encoding=\"utf-8\") as f:\n    f.write(\"name=YYS\")\n\nshutil.copyfile(\"profile.txt\", \"profile.bak\")\nwith open(\"profile.bak\", \"r\", encoding=\"utf-8\") as f:\n    backup_text = f.read()",
      requireCode: ["shutil.copyfile"],
      requiredNames: ["backup_text"],
      assertCode: `assert backup_text == "name=YYS"`,
      failPrefix: "文件备份检查失败：",
      success: "通关！动文件前先备份，工具就更可靠。"
    }),
    makeLesson({
      id: 50,
      level: 7,
      title: "50. 数据流水线 (Data Pipeline)",
      heading: "把读取、清洗、统计串起来",
      concept: "真实数据处理往往是流水线：读取原始数据、清洗、过滤、汇总、输出结果。拆成函数会更清楚。",
      ability: "能写一个小型数据处理流水线函数。",
      example: "def pipeline(rows):\n    cleaned = clean(rows)\n    return summarize(cleaned)",
      task: "请定义函数 `run_pipeline(rows)`：过滤掉 `active` 为 `False` 的记录，并返回活跃记录的 `score` 总和。用给定 `raw_rows` 调用它，结果存入 `pipeline_result`。",
      hint: "在函数里先筛选 active，再 sum 分数。",
      defaultCode: "raw_rows = [{\"active\": True, \"score\": 10}, {\"active\": False, \"score\": 99}, {\"active\": True, \"score\": 15}]\n# 定义 run_pipeline 并计算 pipeline_result\n",
      solution: "raw_rows = [{\"active\": True, \"score\": 10}, {\"active\": False, \"score\": 99}, {\"active\": True, \"score\": 15}]\n\ndef run_pipeline(rows):\n    active_rows = [row for row in rows if row[\"active\"]]\n    return sum(row[\"score\"] for row in active_rows)\n\npipeline_result = run_pipeline(raw_rows)",
      requiredNames: ["run_pipeline", "pipeline_result"],
      assertCode: `assert pipeline_result == 25\nassert run_pipeline([{"active": True, "score": 3}]) == 3`,
      failPrefix: "数据流水线检查失败：",
      success: "Level 7 通关！你已经能把数据处理组织成一条清晰流程。"
    }),
    makeLesson({
      id: 51,
      level: 8,
      title: "51. argparse 参数解析",
      heading: "让脚本接收命令行参数",
      concept: "命令行工具通常通过参数接收用户输入。`argparse` 是 Python 标准库里最常用的参数解析模块。",
      ability: "能创建解析器并解析模拟命令行参数。",
      example: "parser.add_argument(\"--name\")\nargs = parser.parse_args([\"--name\", \"YYS\"])",
      task: "请使用 `argparse.ArgumentParser` 添加参数 `--name` 和 `--count`（整数）。解析参数列表 `[\"--name\", \"YYS\", \"--count\", \"3\"]`，把 `args.name` 存入 `cli_name`，`args.count` 存入 `cli_count`。",
      hint: "count 参数设置 type=int。",
      defaultCode: "# 使用 argparse 解析模拟命令行参数\n",
      solution: "import argparse\n\nparser = argparse.ArgumentParser()\nparser.add_argument(\"--name\")\nparser.add_argument(\"--count\", type=int)\nargs = parser.parse_args([\"--name\", \"YYS\", \"--count\", \"3\"])\ncli_name = args.name\ncli_count = args.count",
      requireCode: ["argparse", "add_argument"],
      requiredNames: ["cli_name", "cli_count"],
      assertCode: `assert cli_name == "YYS"\nassert cli_count == 3`,
      failPrefix: "argparse 检查失败：",
      success: "通关！你的脚本开始有命令行入口了。"
    }),
    makeLesson({
      id: 52,
      level: 8,
      title: "52. 命令分发 (Command Dispatch)",
      heading: "把不同命令交给不同函数",
      concept: "CLI 工具经常有 add、list、delete 等命令。用字典把命令名映射到函数，是轻量清晰的分发方式。",
      ability: "能用函数映射执行不同命令。",
      example: "commands = {\"hello\": hello}\nresult = commands[\"hello\"]()",
      task: "请定义函数 `cmd_hello()` 返回 `\"hello\"`，函数 `cmd_status()` 返回 `\"ok\"`。创建字典 `commands` 映射 `hello/status`，并执行 `commands[\"status\"]()`，结果存入 `dispatch_result`。",
      hint: "字典的值可以是函数本身，不要加括号；调用时再加括号。",
      defaultCode: "# 编写命令分发字典\n",
      solution: "def cmd_hello():\n    return \"hello\"\n\ndef cmd_status():\n    return \"ok\"\n\ncommands = {\n    \"hello\": cmd_hello,\n    \"status\": cmd_status\n}\ndispatch_result = commands[\"status\"]()",
      requiredNames: ["commands", "dispatch_result"],
      assertCode: `assert commands["hello"]() == "hello"\nassert dispatch_result == "ok"`,
      failPrefix: "命令分发检查失败：",
      success: "很好！你可以开始组织多命令工具了。"
    }),
    makeLesson({
      id: 53,
      level: 8,
      title: "53. 菜单循环模型 (Menu Loop)",
      heading: "不用 input 也能练菜单逻辑",
      concept: "真实 CLI 会循环读取用户输入。浏览器里不方便交互输入，所以我们用一串模拟动作来练菜单处理逻辑。",
      ability: "能遍历动作列表并根据命令更新状态。",
      example: "for action in actions:\n    if action == \"add\": ...",
      task: "给定 `actions = [\"add\", \"add\", \"clear\", \"add\"]`，请模拟菜单操作：`add` 让 `item_count` 加 1，`clear` 让它归零。最终 `item_count` 应为 1。",
      hint: "for action in actions，然后 if/elif 判断。",
      defaultCode: "actions = [\"add\", \"add\", \"clear\", \"add\"]\nitem_count = 0\n# 模拟菜单动作\n",
      solution: "actions = [\"add\", \"add\", \"clear\", \"add\"]\nitem_count = 0\nfor action in actions:\n    if action == \"add\":\n        item_count += 1\n    elif action == \"clear\":\n        item_count = 0",
      requiredNames: ["item_count"],
      assertCode: `assert item_count == 1`,
      failPrefix: "菜单循环检查失败：",
      success: "通关！你能把交互动作抽象成可测试流程了。"
    }),
    makeLesson({
      id: 54,
      level: 8,
      title: "54. Todo 命令函数",
      heading: "把任务管理做成函数",
      concept: "命令行工具的核心通常是一组函数：新增、查看、删除、保存。先写纯函数，之后接 CLI 会更稳。",
      ability: "能实现最小 Todo 列表操作函数。",
      example: "def add_todo(todos, title):\n    todos.append({\"title\": title})",
      task: "请定义函数 `add_todo(todos, title)`，向列表追加 `{\"title\": title, \"done\": False}` 并返回列表；定义 `complete_todo(todos, index)`，把对应任务的 done 改为 True 并返回列表。使用它们得到 `todo_state`。",
      hint: "index 是列表下标，直接修改 todos[index]['done']。",
      defaultCode: "todos = []\n# 定义 add_todo 和 complete_todo，并生成 todo_state\n",
      solution: "todos = []\n\ndef add_todo(todos, title):\n    todos.append({\"title\": title, \"done\": False})\n    return todos\n\ndef complete_todo(todos, index):\n    todos[index][\"done\"] = True\n    return todos\n\ntodo_state = add_todo(todos, \"learn cli\")\ntodo_state = complete_todo(todo_state, 0)",
      requiredNames: ["add_todo", "complete_todo", "todo_state"],
      assertCode: `assert todo_state == [{"title": "learn cli", "done": True}]`,
      failPrefix: "Todo 命令函数检查失败：",
      success: "很好！一个可扩展 CLI 工具的业务核心已经出现了。"
    }),
    makeLesson({
      id: 55,
      level: 8,
      title: "55. 文件整理器核心",
      heading: "按扩展名分类文件",
      concept: "文件整理器是非常适合练手的独立工具：扫描文件、判断扩展名、生成目标文件夹。",
      ability: "能根据扩展名生成分类结果。",
      example: "groups.setdefault(ext, []).append(name)",
      task: "给定文件名列表 `files`，请按扩展名分类到字典 `file_groups`，例如 `.png` 下有两个图片文件，`.txt` 下有一个文本文件。",
      hint: "扩展名可以用 name.split('.')[-1] 得到，再加上点。",
      defaultCode: "files = [\"a.png\", \"b.txt\", \"c.png\", \"notes.md\"]\nfile_groups = {}\n# 按扩展名分组\n",
      solution: "files = [\"a.png\", \"b.txt\", \"c.png\", \"notes.md\"]\nfile_groups = {}\nfor name in files:\n    ext = \".\" + name.split(\".\")[-1]\n    file_groups.setdefault(ext, []).append(name)",
      requiredNames: ["file_groups"],
      assertCode: `assert file_groups[".png"] == ["a.png", "c.png"]\nassert file_groups[".txt"] == ["b.txt"]\nassert file_groups[".md"] == ["notes.md"]`,
      failPrefix: "文件整理器检查失败：",
      success: "通关！你已经写出了文件整理工具的核心逻辑。"
    }),
    makeLesson({
      id: 56,
      level: 8,
      title: "56. 模板生成器",
      heading: "用模板批量生成文本",
      concept: "代码生成、报告生成、邮件生成，本质都是模板填充。先学会用字符串模板构造稳定输出。",
      ability: "能根据数据列表批量生成 Markdown 文本。",
      example: "lines = [f\"- {name}\" for name in names]",
      task: "给定 `names = [\"Alice\", \"Bob\"]`，请生成 Markdown 列表字符串 `markdown_list`，内容为两行：`- Alice` 和 `- Bob`。",
      hint: "用列表推导式生成 lines，再 '\\n'.join(lines)。",
      defaultCode: "names = [\"Alice\", \"Bob\"]\n# 生成 markdown_list\n",
      solution: "names = [\"Alice\", \"Bob\"]\nlines = [f\"- {name}\" for name in names]\nmarkdown_list = \"\\n\".join(lines)",
      requiredNames: ["markdown_list"],
      assertCode: `assert markdown_list == "- Alice\\n- Bob"`,
      failPrefix: "模板生成检查失败：",
      success: "很好！你会把结构化数据变成可交付文本了。"
    }),
    makeLesson({
      id: 57,
      level: 8,
      title: "57. 配置驱动工具",
      heading: "让工具行为由配置决定",
      concept: "独立工具应该少写死规则。把规则放进配置，用户或未来的你就能更容易改行为。",
      ability: "能根据配置过滤数据。",
      example: "threshold = config[\"min_score\"]",
      task: "给定 `config = {\"min_score\": 80}` 和 `scores`，请根据配置筛选大于等于阈值的分数，存入 `selected_scores`。",
      hint: "不要写死 80，使用 config['min_score']。",
      defaultCode: "config = {\"min_score\": 80}\nscores = [60, 82, 95, 70]\n# 根据配置筛选 selected_scores\n",
      solution: "config = {\"min_score\": 80}\nscores = [60, 82, 95, 70]\nselected_scores = [score for score in scores if score >= config[\"min_score\"]]",
      requiredNames: ["selected_scores"],
      assertCode: `assert selected_scores == [82, 95]`,
      failPrefix: "配置驱动检查失败：",
      success: "通关！工具开始变得灵活了。"
    }),
    makeLesson({
      id: 58,
      level: 8,
      title: "58. 返回码设计",
      heading: "让命令告诉外界成功或失败",
      concept: "命令行程序常用返回码表达结果：0 表示成功，非 0 表示失败。即使在浏览器里，我们也可以先练这个设计。",
      ability: "能根据执行结果返回标准状态码和消息。",
      example: "return {\"code\": 0, \"message\": \"ok\"}",
      task: "请定义函数 `build_exit_result(success)`：如果 success 为 True，返回 `{\"code\": 0, \"message\": \"ok\"}`；否则返回 `{\"code\": 1, \"message\": \"failed\"}`。将失败结果存入 `exit_result`。",
      hint: "使用 if 判断后返回不同字典。",
      defaultCode: "# 定义 build_exit_result\n",
      solution: "def build_exit_result(success):\n    if success:\n        return {\"code\": 0, \"message\": \"ok\"}\n    return {\"code\": 1, \"message\": \"failed\"}\n\nexit_result = build_exit_result(False)",
      requiredNames: ["build_exit_result", "exit_result"],
      assertCode: `assert build_exit_result(True)["code"] == 0\nassert exit_result == {"code": 1, "message": "failed"}`,
      failPrefix: "返回码设计检查失败：",
      success: "很好！你的工具已经能清楚表达执行结果。"
    }),
    makeLesson({
      id: 59,
      level: 8,
      title: "59. 进度摘要",
      heading: "给长任务一个进度反馈",
      concept: "批处理工具运行时间长时，需要反馈进度。哪怕只是生成一组百分比，也能让用户知道程序没卡住。",
      ability: "能根据总数生成处理进度摘要。",
      example: "percent = int(done / total * 100)",
      task: "给定 `total = 4`，请循环处理 4 个任务，生成列表 `progress_marks = [25, 50, 75, 100]`。",
      hint: "for i in range(1, total + 1)，百分比 int(i / total * 100)。",
      defaultCode: "total = 4\nprogress_marks = []\n# 生成进度百分比\n",
      solution: "total = 4\nprogress_marks = []\nfor i in range(1, total + 1):\n    progress_marks.append(int(i / total * 100))",
      requiredNames: ["progress_marks"],
      assertCode: `assert progress_marks == [25, 50, 75, 100]`,
      failPrefix: "进度摘要检查失败：",
      success: "通关！你的工具开始照顾使用体验了。"
    }),
    makeLesson({
      id: 60,
      level: 8,
      title: "60. CLI 小项目：通讯录核心",
      heading: "把命令、数据、持久化放在一起",
      concept: "通讯录是经典 CLI 项目：新增联系人、查询联系人、保存数据。这个关卡先实现核心类。",
      ability: "能写出一个可保存的通讯录业务核心。",
      example: "book.add(\"Alice\", \"123\")\nbook.find(\"Alice\")",
      task: "请定义类 `ContactBook`：初始化 `self.contacts = {}`；方法 `add(name, phone)` 添加联系人；方法 `find(name)` 查找号码，不存在返回 `None`；方法 `to_json()` 返回 JSON 字符串。创建实例并添加 `Alice -> 123`，查询结果存入 `found_phone`。",
      hint: "to_json 里 import json，然后 json.dumps(self.contacts)。",
      defaultCode: "import json\n\nclass ContactBook:\n    pass\n\n# 创建通讯录并查询 Alice\n",
      solution: "import json\n\nclass ContactBook:\n    def __init__(self):\n        self.contacts = {}\n    def add(self, name, phone):\n        self.contacts[name] = phone\n    def find(self, name):\n        return self.contacts.get(name)\n    def to_json(self):\n        return json.dumps(self.contacts)\n\nbook = ContactBook()\nbook.add(\"Alice\", \"123\")\nfound_phone = book.find(\"Alice\")",
      requiredNames: ["ContactBook", "found_phone"],
      assertCode: `assert found_phone == "123"\nbook2 = ContactBook()\nassert book2.find("Nobody") is None\nbook2.add("Bob", "456")\nimport json\nassert json.loads(book2.to_json()) == {"Bob": "456"}`,
      failPrefix: "通讯录核心检查失败：",
      success: "Level 8 通关！你已经完成了一个 CLI 工具的核心业务模型。"
    }),
    makeLesson({
      id: 61,
      level: 9,
      title: "61. HTTP 响应对象",
      heading: "理解状态码和响应体",
      concept: "Web/API 开发里，请求会得到状态码和响应体。先会处理响应对象，再去接真实网络就不慌。",
      ability: "能根据模拟响应判断请求是否成功。",
      example: "ok = response[\"status\"] == 200",
      task: "给定 `response = {\"status\": 200, \"body\": {\"name\": \"Alice\"}}`，请创建 `is_ok` 判断状态码是否为 200，并把 body 里的 name 存入 `response_name`。",
      hint: "response['body']['name'] 可以取到 Alice。",
      defaultCode: "response = {\"status\": 200, \"body\": {\"name\": \"Alice\"}}\n# 解析响应\n",
      solution: "response = {\"status\": 200, \"body\": {\"name\": \"Alice\"}}\nis_ok = response[\"status\"] == 200\nresponse_name = response[\"body\"][\"name\"]",
      requiredNames: ["is_ok", "response_name"],
      assertCode: `assert is_ok is True\nassert response_name == "Alice"`,
      failPrefix: "HTTP 响应检查失败：",
      success: "通关！你已经理解了 API 响应的基本结构。"
    }),
    makeLesson({
      id: 62,
      level: 9,
      title: "62. URL 查询参数",
      heading: "构造可读的请求地址",
      concept: "API 经常通过查询参数传递筛选条件，比如 `?q=python&page=1`。`urllib.parse.urlencode` 可以安全构造参数。",
      ability: "能用标准库构造带查询参数的 URL。",
      example: "url = base + \"?\" + urlencode(params)",
      task: "请使用 `urllib.parse.urlencode` 将 `params = {\"q\": \"python\", \"page\": 2}` 拼到 `base_url = \"https://api.example.com/search\"` 后面，得到 `full_url`。",
      hint: "from urllib.parse import urlencode。",
      defaultCode: "base_url = \"https://api.example.com/search\"\nparams = {\"q\": \"python\", \"page\": 2}\n# 构造 full_url\n",
      solution: "from urllib.parse import urlencode\n\nbase_url = \"https://api.example.com/search\"\nparams = {\"q\": \"python\", \"page\": 2}\nfull_url = base_url + \"?\" + urlencode(params)",
      requireCode: ["urlencode"],
      requiredNames: ["full_url"],
      assertCode: `assert full_url == "https://api.example.com/search?q=python&page=2"`,
      failPrefix: "URL 参数检查失败：",
      success: "很好！你能构造规范的 API 请求地址了。"
    }),
    makeLesson({
      id: 63,
      level: 9,
      title: "63. API 客户端函数",
      heading: "封装一次请求",
      concept: "项目里不要到处散落请求代码，应该封装成 `fetch_user(id)` 这样的客户端函数，方便测试和替换实现。",
      ability: "能基于模拟响应封装 API 客户端函数。",
      example: "def fetch_user(user_id):\n    return api_data[user_id]",
      task: "给定模拟数据 `API_DATA`，请定义函数 `fetch_user(user_id)`：如果用户存在，返回对应字典；否则返回 `None`。调用 `fetch_user(2)`，结果存入 `api_user`。",
      hint: "可以用 API_DATA.get(user_id)。",
      defaultCode: "API_DATA = {1: {\"name\": \"Alice\"}, 2: {\"name\": \"Bob\"}}\n# 定义 fetch_user\n",
      solution: "API_DATA = {1: {\"name\": \"Alice\"}, 2: {\"name\": \"Bob\"}}\n\ndef fetch_user(user_id):\n    return API_DATA.get(user_id)\n\napi_user = fetch_user(2)",
      requiredNames: ["fetch_user", "api_user"],
      assertCode: `assert api_user == {"name": "Bob"}\nassert fetch_user(99) is None`,
      failPrefix: "API 客户端检查失败：",
      success: "通关！你开始把外部接口封装成可复用函数了。"
    }),
    makeLesson({
      id: 64,
      level: 9,
      title: "64. 路由表思维",
      heading: "Web 应用如何分发请求",
      concept: "Flask/FastAPI 里的路由，本质是把路径映射到处理函数。即使不运行真实服务器，也可以先练路由表思维。",
      ability: "能用字典模拟路径到处理函数的分发。",
      example: "routes = {\"/\": home}\nresult = routes[\"/\"]()",
      task: "请定义函数 `home()` 返回 `\"home page\"`，函数 `about()` 返回 `\"about page\"`。创建 `routes` 字典映射 `/` 和 `/about`，再把 `/about` 的处理结果存入 `route_result`。",
      hint: "routes['/about']() 调用 about 函数。",
      defaultCode: "# 模拟 Web 路由表\n",
      solution: "def home():\n    return \"home page\"\n\ndef about():\n    return \"about page\"\n\nroutes = {\n    \"/\": home,\n    \"/about\": about\n}\nroute_result = routes[\"/about\"]()",
      requiredNames: ["routes", "route_result"],
      assertCode: `assert routes["/"]() == "home page"\nassert route_result == "about page"`,
      failPrefix: "路由表检查失败：",
      success: "很好！你已经理解了 Web 路由的核心抽象。"
    }),
    makeLesson({
      id: 65,
      level: 9,
      title: "65. JSON API 响应",
      heading: "统一接口输出格式",
      concept: "好的 API 通常有统一响应格式，比如 `success/data/error`。统一格式能让前端和调用方更容易处理。",
      ability: "能构造标准 JSON API 响应字典。",
      example: "return {\"success\": True, \"data\": data, \"error\": None}",
      task: "请定义函数 `make_response(data=None, error=None)`：如果 error 是 None，返回 `{\"success\": True, \"data\": data, \"error\": None}`；否则返回 `{\"success\": False, \"data\": None, \"error\": error}`。创建 `api_response = make_response({\"id\": 1})`。",
      hint: "用 if error is None 判断。",
      defaultCode: "# 定义统一 API 响应函数\n",
      solution: "def make_response(data=None, error=None):\n    if error is None:\n        return {\"success\": True, \"data\": data, \"error\": None}\n    return {\"success\": False, \"data\": None, \"error\": error}\n\napi_response = make_response({\"id\": 1})",
      requiredNames: ["make_response", "api_response"],
      assertCode: `assert api_response == {"success": True, "data": {"id": 1}, "error": None}\nassert make_response(error="bad") == {"success": False, "data": None, "error": "bad"}`,
      failPrefix: "API 响应检查失败：",
      success: "通关！你的接口输出开始有统一契约了。"
    }),
    makeLesson({
      id: 66,
      level: 9,
      title: "66. HTML 模板渲染",
      heading: "把数据放进页面",
      concept: "Web 页面通常由模板和数据组合而成。先用字符串模拟模板渲染，能理解后端渲染的基本原理。",
      ability: "能根据数据生成简单 HTML 字符串。",
      example: "html = f\"<h1>{title}</h1>\"",
      task: "给定 `user = {\"name\": \"Alice\", \"score\": 90}`，请生成字符串 `html`，包含 `<h1>Alice</h1>` 和 `<p>Score: 90</p>`。",
      hint: "用 f-string 拼接 HTML。",
      defaultCode: "user = {\"name\": \"Alice\", \"score\": 90}\n# 生成 html\n",
      solution: "user = {\"name\": \"Alice\", \"score\": 90}\nhtml = f\"<h1>{user['name']}</h1>\\n<p>Score: {user['score']}</p>\"",
      requiredNames: ["html"],
      assertCode: `assert "<h1>Alice</h1>" in html\nassert "<p>Score: 90</p>" in html`,
      failPrefix: "HTML 模板检查失败：",
      success: "很好！你理解了数据如何进入页面。"
    }),
    makeLesson({
      id: 67,
      level: 9,
      title: "67. 表单校验",
      heading: "接收用户输入前先验证",
      concept: "Web 表单不能信任用户输入。后端需要校验必填字段、格式和业务规则，再决定是否接受。",
      ability: "能写基础表单校验函数，返回错误列表。",
      example: "errors = []\nif not form[\"name\"]: errors.append(\"name required\")",
      task: "请定义函数 `validate_form(form)`：如果 `name` 为空，加入错误 `\"name required\"`；如果 `age` 小于 0，加入 `\"age invalid\"`；最后返回错误列表。用 `{\"name\": \"\", \"age\": -1}` 调用，结果存入 `form_errors`。",
      hint: "errors 是列表，逐项 append。",
      defaultCode: "# 定义 validate_form\n",
      solution: "def validate_form(form):\n    errors = []\n    if not form.get(\"name\"):\n        errors.append(\"name required\")\n    if form.get(\"age\", 0) < 0:\n        errors.append(\"age invalid\")\n    return errors\n\nform_errors = validate_form({\"name\": \"\", \"age\": -1})",
      requiredNames: ["validate_form", "form_errors"],
      assertCode: `assert form_errors == ["name required", "age invalid"]\nassert validate_form({"name": "Alice", "age": 20}) == []`,
      failPrefix: "表单校验检查失败：",
      success: "通关！你的应用开始能防住坏输入了。"
    }),
    makeLesson({
      id: 68,
      level: 9,
      title: "68. REST CRUD 模拟",
      heading: "理解增删改查接口",
      concept: "REST API 常围绕资源做增删改查。用字典模拟数据库，可以先练清楚接口行为。",
      ability: "能实现 create/read/update/delete 四类资源操作。",
      example: "store[id] = item\nreturn store.get(id)",
      task: "请定义字典 `store = {}`，函数 `create_item(item_id, data)` 保存数据，函数 `read_item(item_id)` 读取数据，函数 `delete_item(item_id)` 删除并返回被删数据。创建一条 id 为 1 的数据并读取到 `crud_result`。",
      hint: "delete 可以用 pop(item_id, None)。",
      defaultCode: "store = {}\n# 定义 create_item/read_item/delete_item\n",
      solution: "store = {}\n\ndef create_item(item_id, data):\n    store[item_id] = data\n    return data\n\ndef read_item(item_id):\n    return store.get(item_id)\n\ndef delete_item(item_id):\n    return store.pop(item_id, None)\n\ncreate_item(1, {\"name\": \"book\"})\ncrud_result = read_item(1)",
      requiredNames: ["store", "create_item", "read_item", "delete_item", "crud_result"],
      assertCode: `assert crud_result == {"name": "book"}\nassert delete_item(1) == {"name": "book"}\nassert read_item(1) is None`,
      failPrefix: "CRUD 检查失败：",
      success: "很好！你已经理解了资源型接口的基本动作。"
    }),
    makeLesson({
      id: 69,
      level: 9,
      title: "69. 分页返回 (Pagination)",
      heading: "不要一次返回所有数据",
      concept: "数据多时，API 通常分页返回。分页需要 page、page_size、total 和当前页数据。",
      ability: "能实现列表分页函数。",
      example: "start = (page - 1) * page_size\nitems[start:start + page_size]",
      task: "请定义函数 `paginate(items, page, page_size)`，返回字典：`items` 为当前页数据，`total` 为总数。对 `list(range(1, 11))` 取第 2 页、每页 3 条，结果存入 `page_result`。",
      hint: "第 2 页每页 3 条，应得到 [4, 5, 6]。",
      defaultCode: "# 定义 paginate\n",
      solution: "def paginate(items, page, page_size):\n    start = (page - 1) * page_size\n    end = start + page_size\n    return {\"items\": items[start:end], \"total\": len(items)}\n\npage_result = paginate(list(range(1, 11)), 2, 3)",
      requiredNames: ["paginate", "page_result"],
      assertCode: `assert page_result == {"items": [4, 5, 6], "total": 10}`,
      failPrefix: "分页检查失败：",
      success: "通关！你的 API 已经开始考虑数据量了。"
    }),
    makeLesson({
      id: 70,
      level: 9,
      title: "70. Web 小项目：天气接口聚合",
      heading: "封装一个 API 工具函数",
      concept: "天气、汇率、新闻等工具的核心都是：请求数据、提取关键信息、返回统一结果。这里用模拟数据练完整流程。",
      ability: "能封装一个从模拟 API 中提取业务结果的函数。",
      example: "return {\"city\": city, \"temp\": data[city][\"temp\"]}",
      task: "给定 `WEATHER_API` 字典，请定义函数 `get_weather(city)`：城市存在时返回 `{\"city\": city, \"temp\": 温度, \"text\": 天气}`，不存在时返回 `None`。调用 `get_weather(\"Shanghai\")` 存入 `weather_result`。",
      hint: "先 if city not in WEATHER_API: return None。",
      defaultCode: "WEATHER_API = {\"Shanghai\": {\"temp\": 26, \"text\": \"Sunny\"}, \"Beijing\": {\"temp\": 20, \"text\": \"Cloudy\"}}\n# 定义 get_weather\n",
      solution: "WEATHER_API = {\"Shanghai\": {\"temp\": 26, \"text\": \"Sunny\"}, \"Beijing\": {\"temp\": 20, \"text\": \"Cloudy\"}}\n\ndef get_weather(city):\n    if city not in WEATHER_API:\n        return None\n    data = WEATHER_API[city]\n    return {\"city\": city, \"temp\": data[\"temp\"], \"text\": data[\"text\"]}\n\nweather_result = get_weather(\"Shanghai\")",
      requiredNames: ["get_weather", "weather_result"],
      assertCode: `assert weather_result == {"city": "Shanghai", "temp": 26, "text": "Sunny"}\nassert get_weather("Nowhere") is None`,
      failPrefix: "天气接口聚合检查失败：",
      success: "Level 9 通关！你已经能用 Web/API 思维封装数据服务。"
    }),
    makeLesson({
      id: 71,
      level: 10,
      title: "71. SQLite 建表",
      heading: "把数据放进真正的数据库",
      concept: "SQLite 是 Python 内置支持的轻量数据库，非常适合个人工具、小项目和本地应用。",
      ability: "能连接内存数据库并创建表。",
      example: "conn = sqlite3.connect(\":memory:\")\nconn.execute(\"CREATE TABLE users ...\")",
      task: "请导入 `sqlite3`，连接内存数据库，创建表 `users(id INTEGER, name TEXT)`，并把表名列表存入 `table_names`。",
      hint: "从 sqlite_master 查询表名。",
      defaultCode: "# 使用 sqlite3 创建 users 表\n",
      solution: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.execute(\"CREATE TABLE users (id INTEGER, name TEXT)\")\ntable_names = [row[0] for row in conn.execute(\"SELECT name FROM sqlite_master WHERE type='table'\")]",
      requireCode: ["sqlite3", "CREATE TABLE"],
      requiredNames: ["table_names"],
      assertCode: `assert "users" in table_names`,
      failPrefix: "SQLite 建表检查失败：",
      success: "通关！你已经迈进数据库开发的大门。"
    }),
    makeLesson({
      id: 72,
      level: 10,
      title: "72. 插入与查询",
      heading: "写入数据，再读出来",
      concept: "数据库最基础的动作是 INSERT 和 SELECT。掌握它们后，就能保存和读取应用数据。",
      ability: "能向 SQLite 表插入记录并查询。",
      example: "conn.execute(\"INSERT INTO users VALUES (?, ?)\", (1, \"Alice\"))",
      task: "请创建内存数据库和 `users` 表，插入 `(1, \"Alice\")`，查询 name 并存入 `db_user_name`。",
      hint: "使用 fetchone()[0] 取查询结果。",
      defaultCode: "# 插入并查询 SQLite 数据\n",
      solution: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.execute(\"CREATE TABLE users (id INTEGER, name TEXT)\")\nconn.execute(\"INSERT INTO users VALUES (?, ?)\", (1, \"Alice\"))\ndb_user_name = conn.execute(\"SELECT name FROM users WHERE id = ?\", (1,)).fetchone()[0]",
      requireCode: ["INSERT INTO", "SELECT"],
      requiredNames: ["db_user_name"],
      assertCode: `assert db_user_name == "Alice"`,
      failPrefix: "插入查询检查失败：",
      success: "很好！你的程序可以把数据持久化到数据库结构里了。"
    }),
    makeLesson({
      id: 73,
      level: 10,
      title: "73. 参数化查询",
      heading: "避免 SQL 注入",
      concept: "SQL 里不要用字符串拼接用户输入。参数化查询用 `?` 占位，可以更安全地传入值。",
      ability: "能用参数化方式查询数据。",
      example: "cursor.execute(\"SELECT * FROM users WHERE id=?\", (user_id,))",
      task: "请创建函数 `find_user(conn, user_id)`，使用参数化查询 `?` 查询用户 name。插入 Alice 后，调用 `find_user(conn, 1)`，结果存入 `safe_query_name`。",
      hint: "execute 的第二个参数是元组，单元素元组写 `(user_id,)`。",
      defaultCode: "# 使用参数化查询查找用户\n",
      solution: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.execute(\"CREATE TABLE users (id INTEGER, name TEXT)\")\nconn.execute(\"INSERT INTO users VALUES (?, ?)\", (1, \"Alice\"))\n\ndef find_user(conn, user_id):\n    row = conn.execute(\"SELECT name FROM users WHERE id = ?\", (user_id,)).fetchone()\n    return row[0] if row else None\n\nsafe_query_name = find_user(conn, 1)",
      requireCode: ["?"],
      requiredNames: ["find_user", "safe_query_name"],
      assertCode: `assert safe_query_name == "Alice"\nassert find_user(conn, 99) is None`,
      failPrefix: "参数化查询检查失败：",
      success: "通关！你已经开始写更安全的数据库代码。"
    }),
    makeLesson({
      id: 74,
      level: 10,
      title: "74. 更新与删除",
      heading: "维护数据库里的数据",
      concept: "应用不仅会新增数据，还要修改状态、删除记录。UPDATE 和 DELETE 是完整 CRUD 的关键。",
      ability: "能更新和删除 SQLite 记录。",
      example: "UPDATE todos SET done=1 WHERE id=?",
      task: "请创建 `todos` 表，插入一条 `(1, \"learn\", 0)`，将 done 更新为 1，再删除这条记录。把删除后的剩余数量存入 `remaining_count`。",
      hint: "SELECT COUNT(*) FROM todos 可以统计数量。",
      defaultCode: "# 更新并删除 SQLite 记录\n",
      solution: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.execute(\"CREATE TABLE todos (id INTEGER, title TEXT, done INTEGER)\")\nconn.execute(\"INSERT INTO todos VALUES (?, ?, ?)\", (1, \"learn\", 0))\nconn.execute(\"UPDATE todos SET done = 1 WHERE id = ?\", (1,))\nconn.execute(\"DELETE FROM todos WHERE id = ?\", (1,))\nremaining_count = conn.execute(\"SELECT COUNT(*) FROM todos\").fetchone()[0]",
      requireCode: ["UPDATE", "DELETE"],
      requiredNames: ["remaining_count"],
      assertCode: `assert remaining_count == 0`,
      failPrefix: "更新删除检查失败：",
      success: "很好！数据库 CRUD 闭环已经完整了。"
    }),
    makeLesson({
      id: 75,
      level: 10,
      title: "75. 一对多关系",
      heading: "用外键思维连接数据",
      concept: "用户有多条任务、作者有多篇文章，这就是一对多关系。即使暂不启用外键约束，也要知道如何用 id 关联。",
      ability: "能通过 user_id 查询某个用户的所有任务。",
      example: "SELECT title FROM todos WHERE user_id=?",
      task: "请创建 `users` 与 `todos` 两张表，插入用户 Alice 以及她的两个任务。查询 Alice 的任务标题列表，存入 `alice_todos`。",
      hint: "todos 表可包含 id, user_id, title 三列。",
      defaultCode: "# 使用 user_id 关联用户和任务\n",
      solution: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.execute(\"CREATE TABLE users (id INTEGER, name TEXT)\")\nconn.execute(\"CREATE TABLE todos (id INTEGER, user_id INTEGER, title TEXT)\")\nconn.execute(\"INSERT INTO users VALUES (?, ?)\", (1, \"Alice\"))\nconn.execute(\"INSERT INTO todos VALUES (?, ?, ?)\", (1, 1, \"learn\"))\nconn.execute(\"INSERT INTO todos VALUES (?, ?, ?)\", (2, 1, \"ship\"))\nalice_todos = [row[0] for row in conn.execute(\"SELECT title FROM todos WHERE user_id = ? ORDER BY id\", (1,))]",
      requireCode: ["CREATE TABLE users", "CREATE TABLE todos"],
      requiredNames: ["alice_todos"],
      assertCode: `assert alice_todos == ["learn", "ship"]`,
      failPrefix: "一对多关系检查失败：",
      success: "通关！你能用数据库表达真实业务关系了。"
    }),
    makeLesson({
      id: 76,
      level: 10,
      title: "76. 事务提交",
      heading: "一组操作要么都成功，要么都不做",
      concept: "事务能保证数据一致性。Python 的 sqlite 连接可配合 `with conn:` 自动提交或回滚。",
      ability: "能使用事务语法写入多条数据。",
      example: "with conn:\n    conn.execute(...)",
      task: "请创建 `items` 表，并在 `with conn:` 事务块中插入两条数据。最后统计数量到 `item_count`。",
      hint: "with conn: 下面连续执行两次 INSERT。",
      defaultCode: "# 使用事务插入多条数据\n",
      solution: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.execute(\"CREATE TABLE items (id INTEGER, name TEXT)\")\nwith conn:\n    conn.execute(\"INSERT INTO items VALUES (?, ?)\", (1, \"A\"))\n    conn.execute(\"INSERT INTO items VALUES (?, ?)\", (2, \"B\"))\nitem_count = conn.execute(\"SELECT COUNT(*) FROM items\").fetchone()[0]",
      requireCode: ["with conn"],
      requiredNames: ["item_count"],
      assertCode: `assert item_count == 2`,
      failPrefix: "事务检查失败：",
      success: "很好！你已经开始考虑数据库写入的一致性。"
    }),
    makeLesson({
      id: 77,
      level: 10,
      title: "77. Repository 模式",
      heading: "把数据库操作封装成类",
      concept: "不要让 SQL 散落在业务代码里。Repository 类可以集中管理某类数据的存取。",
      ability: "能写一个简单 Repository 封装新增和查询。",
      example: "repo.add(\"Alice\")\nrepo.list_names()",
      task: "请定义类 `UserRepository`，构造时接收 `conn`；方法 `add_user(name)` 插入用户；方法 `list_users()` 返回所有用户名列表。创建 repo，添加 Alice 和 Bob，结果存入 `repo_users`。",
      hint: "构造方法里保存 self.conn。",
      defaultCode: "import sqlite3\n\n# 定义 UserRepository\n",
      solution: "import sqlite3\n\nclass UserRepository:\n    def __init__(self, conn):\n        self.conn = conn\n        self.conn.execute(\"CREATE TABLE IF NOT EXISTS users (name TEXT)\")\n    def add_user(self, name):\n        self.conn.execute(\"INSERT INTO users VALUES (?)\", (name,))\n    def list_users(self):\n        return [row[0] for row in self.conn.execute(\"SELECT name FROM users ORDER BY name\")]\n\nconn = sqlite3.connect(\":memory:\")\nrepo = UserRepository(conn)\nrepo.add_user(\"Bob\")\nrepo.add_user(\"Alice\")\nrepo_users = repo.list_users()",
      requiredNames: ["UserRepository", "repo_users"],
      assertCode: `assert repo_users == ["Alice", "Bob"]`,
      failPrefix: "Repository 检查失败：",
      success: "通关！数据库访问已经被你封装成可维护类了。"
    }),
    makeLesson({
      id: 78,
      level: 10,
      title: "78. 迁移版本 (Migrations)",
      heading: "记录数据库结构版本",
      concept: "项目升级时，数据库结构也会变化。迁移版本表可以记录哪些结构变更已经执行过。",
      ability: "能创建迁移记录表并写入版本号。",
      example: "CREATE TABLE migrations(version TEXT)",
      task: "请创建表 `migrations(version TEXT)`，插入版本 `\"001_create_users\"`，查询版本列表到 `applied_migrations`。",
      hint: "这关关注迁移记录，不需要真的改多张表。",
      defaultCode: "# 创建 migrations 表并记录版本\n",
      solution: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.execute(\"CREATE TABLE migrations (version TEXT)\")\nconn.execute(\"INSERT INTO migrations VALUES (?)\", (\"001_create_users\",))\napplied_migrations = [row[0] for row in conn.execute(\"SELECT version FROM migrations\")]",
      requiredNames: ["applied_migrations"],
      assertCode: `assert applied_migrations == ["001_create_users"]`,
      failPrefix: "迁移版本检查失败：",
      success: "很好！你开始理解项目升级时数据库也需要管理。"
    }),
    makeLesson({
      id: 79,
      level: 10,
      title: "79. 数据库搜索",
      heading: "用 LIKE 做简单搜索",
      concept: "搜索是应用常见功能。SQLite 的 LIKE 可以完成简单模糊匹配。",
      ability: "能按关键词搜索数据库记录。",
      example: "WHERE title LIKE ?",
      task: "请创建 notes 表，插入 `Python tips`、`Java notes`、`Python project`。搜索标题包含 `Python` 的记录，标题列表存入 `python_notes`。",
      hint: "LIKE 参数可以是 `%Python%`。",
      defaultCode: "# 使用 LIKE 搜索 notes\n",
      solution: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.execute(\"CREATE TABLE notes (title TEXT)\")\nfor title in [\"Python tips\", \"Java notes\", \"Python project\"]:\n    conn.execute(\"INSERT INTO notes VALUES (?)\", (title,))\npython_notes = [row[0] for row in conn.execute(\"SELECT title FROM notes WHERE title LIKE ? ORDER BY title\", (\"%Python%\",))]",
      requireCode: ["LIKE"],
      requiredNames: ["python_notes"],
      assertCode: `assert python_notes == ["Python project", "Python tips"]`,
      failPrefix: "数据库搜索检查失败：",
      success: "通关！你能为应用添加基础搜索能力了。"
    }),
    makeLesson({
      id: 80,
      level: 10,
      title: "80. 数据库小项目：图书馆",
      heading: "用 SQLite 管理一个小资源",
      concept: "图书馆系统是 CRUD 和搜索的组合练习。先用类封装数据库操作，就能逐渐发展成完整应用。",
      ability: "能写一个基于 SQLite 的小型资源管理类。",
      example: "library.add_book(\"Python\")\nlibrary.list_books()",
      task: "请定义类 `LibraryDB`：初始化时创建 books 表；方法 `add_book(title)` 插入书名；方法 `list_books()` 返回按标题排序的书名列表。添加 `Python` 和 `Flask`，结果存入 `books`。",
      hint: "类内部保存 conn，list_books 用 SELECT title FROM books ORDER BY title。",
      defaultCode: "import sqlite3\n\nclass LibraryDB:\n    pass\n\n# 添加两本书并查询\n",
      solution: "import sqlite3\n\nclass LibraryDB:\n    def __init__(self):\n        self.conn = sqlite3.connect(\":memory:\")\n        self.conn.execute(\"CREATE TABLE books (title TEXT)\")\n    def add_book(self, title):\n        self.conn.execute(\"INSERT INTO books VALUES (?)\", (title,))\n    def list_books(self):\n        return [row[0] for row in self.conn.execute(\"SELECT title FROM books ORDER BY title\")]\n\nlibrary = LibraryDB()\nlibrary.add_book(\"Python\")\nlibrary.add_book(\"Flask\")\nbooks = library.list_books()",
      requiredNames: ["LibraryDB", "books"],
      assertCode: `assert books == ["Flask", "Python"]`,
      failPrefix: "图书馆数据库检查失败：",
      success: "Level 10 通关！你已经能用数据库支撑一个小项目了。"
    }),
    makeLesson({
      id: 81,
      level: 11,
      title: "81. unittest 单元测试",
      heading: "用测试保护函数",
      concept: "独立开发不是写完就算。单元测试能帮你确认函数在修改后仍然正确。",
      ability: "能用 unittest 写一个基础测试类。",
      example: "class TestAdd(unittest.TestCase):\n    def test_add(self): ...",
      task: "请导入 `unittest`，定义函数 `add(a, b)`，再定义测试类 `TestAdd(unittest.TestCase)`，其中 `test_add` 使用 `self.assertEqual(add(2, 3), 5)`。",
      hint: "这关不需要运行 unittest.main，只要定义测试类和方法。",
      defaultCode: "# 定义 add 和 unittest 测试类\n",
      solution: "import unittest\n\ndef add(a, b):\n    return a + b\n\nclass TestAdd(unittest.TestCase):\n    def test_add(self):\n        self.assertEqual(add(2, 3), 5)",
      requireCode: ["unittest", "assertEqual"],
      requiredNames: ["add", "TestAdd"],
      assertCode: `case = TestAdd("test_add")\ncase.test_add()\nassert add(10, 5) == 15`,
      failPrefix: "unittest 检查失败：",
      success: "通关！你已经开始用测试保护代码了。"
    }),
    makeLesson({
      id: 82,
      level: 11,
      title: "82. 测试边界值",
      heading: "正常情况之外也要测",
      concept: "只测正常输入不够。边界值、空列表、0、None 往往最容易出 bug。",
      ability: "能为函数设计边界行为。",
      example: "if not numbers: return 0",
      task: "请定义函数 `average(numbers)`：空列表返回 0，否则返回平均值。再创建 `avg_empty` 和 `avg_normal` 分别保存 `average([])` 与 `average([2, 4, 6])`。",
      hint: "先判断 if not numbers。",
      defaultCode: "# 定义 average 并测试空列表\n",
      solution: "def average(numbers):\n    if not numbers:\n        return 0\n    return sum(numbers) / len(numbers)\n\navg_empty = average([])\navg_normal = average([2, 4, 6])",
      requiredNames: ["average", "avg_empty", "avg_normal"],
      assertCode: `assert avg_empty == 0\nassert avg_normal == 4\nassert average([10]) == 10`,
      failPrefix: "边界值检查失败：",
      success: "很好！你开始主动处理边界情况了。"
    }),
    makeLesson({
      id: 83,
      level: 11,
      title: "83. doctest 文档测试",
      heading: "让示例也能被验证",
      concept: "doctest 可以检查文档字符串里的示例是否真的能跑通。它让说明文档和测试结合起来。",
      ability: "能写带示例的函数文档字符串。",
      example: "def square(x):\n    \"\"\">>> square(3)\n    9\"\"\"",
      task: "请定义函数 `square(x)`，返回平方，并在文档字符串里包含示例 `>>> square(3)` 下一行 `9`。创建 `square_doc` 保存该函数的 `__doc__`。",
      hint: "三引号文档字符串写在函数第一行。",
      defaultCode: "# 定义带 doctest 示例的 square\n",
      solution: "def square(x):\n    \"\"\"\n    >>> square(3)\n    9\n    \"\"\"\n    return x * x\n\nsquare_doc = square.__doc__",
      requireCode: [">>> square(3)"],
      requiredNames: ["square", "square_doc"],
      assertCode: `assert square(4) == 16\nassert ">>> square(3)" in square_doc\nassert "9" in square_doc`,
      failPrefix: "doctest 检查失败：",
      success: "通关！你的示例开始具备可验证性了。"
    }),
    makeLesson({
      id: 84,
      level: 11,
      title: "84. 依赖注入",
      heading: "让函数更容易测试",
      concept: "如果函数直接依赖外部服务，会难测试。把依赖作为参数传进去，就能在测试时替换成假对象。",
      ability: "能把数据源函数作为依赖传入业务函数。",
      example: "def load_name(fetcher):\n    return fetcher()[\"name\"]",
      task: "请定义函数 `get_user_name(fetch_user, user_id)`，调用传入的 `fetch_user(user_id)` 并返回用户 name。定义 `fake_fetch_user` 返回 `{\"name\": \"Alice\"}`，将结果存入 `injected_name`。",
      hint: "get_user_name 不要直接读取全局数据，而是调用参数 fetch_user。",
      defaultCode: "# 使用依赖注入获取用户名\n",
      solution: "def get_user_name(fetch_user, user_id):\n    user = fetch_user(user_id)\n    return user[\"name\"]\n\ndef fake_fetch_user(user_id):\n    return {\"name\": \"Alice\"}\n\ninjected_name = get_user_name(fake_fetch_user, 1)",
      requiredNames: ["get_user_name", "fake_fetch_user", "injected_name"],
      assertCode: `assert injected_name == "Alice"`,
      failPrefix: "依赖注入检查失败：",
      success: "很好！你的业务逻辑更容易测试和替换依赖了。"
    }),
    makeLesson({
      id: 85,
      level: 11,
      title: "85. 纯函数重构",
      heading: "少依赖外部状态",
      concept: "纯函数只依赖输入并返回输出，不偷偷修改外部状态。它更容易测试、复用和调试。",
      ability: "能把计算逻辑写成不修改原数据的函数。",
      example: "def add_tax(price): return price * 1.1",
      task: "请定义函数 `apply_discount(prices, rate)`，返回打折后的新列表，不修改原列表。给定 `prices = [100, 200]`，计算 `discounted_prices`。",
      hint: "返回 [price * (1 - rate) for price in prices]。",
      defaultCode: "prices = [100, 200]\n# 定义 apply_discount 并生成 discounted_prices\n",
      solution: "prices = [100, 200]\n\ndef apply_discount(prices, rate):\n    return [price * (1 - rate) for price in prices]\n\ndiscounted_prices = apply_discount(prices, 0.2)",
      requiredNames: ["apply_discount", "discounted_prices"],
      assertCode: `assert discounted_prices == [80.0, 160.0]\nassert prices == [100, 200]`,
      failPrefix: "纯函数检查失败：",
      success: "通关！你的函数更容易测试，也更不容易制造副作用。"
    }),
    makeLesson({
      id: 86,
      level: 11,
      title: "86. 自定义异常",
      heading: "用明确异常表达业务错误",
      concept: "自定义异常可以让业务错误更清楚，比如余额不足、权限不够、数据不存在。",
      ability: "能定义并抛出自定义异常。",
      example: "class AppError(Exception): pass",
      task: "请定义异常类 `InsufficientBalanceError(Exception)`。定义函数 `withdraw(balance, amount)`：如果 amount 大于 balance，抛出该异常；否则返回剩余余额。将 `withdraw(100, 30)` 存入 `left_balance`。",
      hint: "raise InsufficientBalanceError(\"...\")。",
      defaultCode: "# 定义余额不足异常和 withdraw 函数\n",
      solution: "class InsufficientBalanceError(Exception):\n    pass\n\ndef withdraw(balance, amount):\n    if amount > balance:\n        raise InsufficientBalanceError(\"not enough balance\")\n    return balance - amount\n\nleft_balance = withdraw(100, 30)",
      requireCode: ["raise"],
      requiredNames: ["InsufficientBalanceError", "withdraw", "left_balance"],
      assertCode: `assert left_balance == 70\ntry:\n    withdraw(10, 20)\n    raise AssertionError("余额不足时应抛出异常")\nexcept InsufficientBalanceError:\n    pass`,
      failPrefix: "自定义异常检查失败：",
      success: "很好！你的错误处理开始有业务语义了。"
    }),
    makeLesson({
      id: 87,
      level: 11,
      title: "87. 数据模型校验",
      heading: "先校验，再保存",
      concept: "无论 CLI、Web 还是数据库应用，数据进入系统前都应该验证字段完整性和类型。",
      ability: "能写一个返回错误列表的数据校验函数。",
      example: "if \"email\" not in user: errors.append(...)",
      task: "请定义函数 `validate_user(user)`：如果缺少 `name`，加入 `\"name missing\"`；如果 `age` 不是 int，加入 `\"age invalid\"`。用 `{\"age\": \"18\"}` 调用，结果存入 `user_errors`。",
      hint: "用 isinstance(user.get('age'), int) 判断类型。",
      defaultCode: "# 定义 validate_user\n",
      solution: "def validate_user(user):\n    errors = []\n    if not user.get(\"name\"):\n        errors.append(\"name missing\")\n    if not isinstance(user.get(\"age\"), int):\n        errors.append(\"age invalid\")\n    return errors\n\nuser_errors = validate_user({\"age\": \"18\"})",
      requiredNames: ["validate_user", "user_errors"],
      assertCode: `assert user_errors == ["name missing", "age invalid"]\nassert validate_user({"name": "Alice", "age": 18}) == []`,
      failPrefix: "数据校验检查失败：",
      success: "通关！你的应用开始具备输入防线了。"
    }),
    makeLesson({
      id: 88,
      level: 11,
      title: "88. 服务层设计",
      heading: "把业务逻辑从存储里分离",
      concept: "Repository 负责存取，Service 负责业务规则。分层能让项目长大后仍然清晰。",
      ability: "能写一个调用 repository 的 service 类。",
      example: "class UserService:\n    def __init__(self, repo): self.repo = repo",
      task: "请定义类 `UserService`，构造时接收 `repo`。方法 `register(name)`：如果 name 为空返回 `False`，否则调用 `repo.add(name)` 并返回 `True`。用假的 repo 测试，结果存入 `service_result`。",
      hint: "FakeRepo 可以有 names 列表和 add 方法。",
      defaultCode: "# 定义 UserService 和 FakeRepo\n",
      solution: "class UserService:\n    def __init__(self, repo):\n        self.repo = repo\n    def register(self, name):\n        if not name:\n            return False\n        self.repo.add(name)\n        return True\n\nclass FakeRepo:\n    def __init__(self):\n        self.names = []\n    def add(self, name):\n        self.names.append(name)\n\nfake_repo = FakeRepo()\nservice = UserService(fake_repo)\nservice_result = service.register(\"Alice\")",
      requiredNames: ["UserService", "FakeRepo", "service_result"],
      assertCode: `assert service_result is True\nassert fake_repo.names == ["Alice"]\nassert service.register("") is False`,
      failPrefix: "服务层检查失败：",
      success: "很好！你开始用分层结构组织业务代码了。"
    }),
    makeLesson({
      id: 89,
      level: 11,
      title: "89. 简单性能意识",
      heading: "别让循环白白变慢",
      concept: "独立开发不需要一开始就追求极致性能，但要知道集合查找通常比列表反复查找更适合做去重和包含判断。",
      ability: "能用 set 做快速交集筛选。",
      example: "selected = [x for x in a if x in set_b]",
      task: "给定 `all_users` 和 `active_users`，请先把 active_users 转成集合 `active_set`，再筛选出仍活跃的用户 `visible_users`。",
      hint: "visible_users = [u for u in all_users if u in active_set]。",
      defaultCode: "all_users = [\"A\", \"B\", \"C\", \"D\"]\nactive_users = [\"B\", \"D\"]\n# 使用 set 筛选 visible_users\n",
      solution: "all_users = [\"A\", \"B\", \"C\", \"D\"]\nactive_users = [\"B\", \"D\"]\nactive_set = set(active_users)\nvisible_users = [user for user in all_users if user in active_set]",
      requiredNames: ["active_set", "visible_users"],
      assertCode: `assert active_set == {"B", "D"}\nassert visible_users == ["B", "D"]`,
      failPrefix: "性能意识检查失败：",
      success: "通关！你开始知道什么时候该换数据结构了。"
    }),
    makeLesson({
      id: 90,
      level: 11,
      title: "90. 质量小项目：带测试的计算器",
      heading: "功能和测试一起交付",
      concept: "真正独立开发时，重要逻辑最好配套测试。这个关卡把函数、异常、测试断言合在一起。",
      ability: "能实现一个带错误处理和自测的迷你模块。",
      example: "assert divide(6, 3) == 2",
      task: "请定义函数 `divide(a, b)`：b 为 0 时抛出 `ValueError(\"b cannot be zero\")`，否则返回除法结果。再创建列表 `self_checks`，包含两个布尔检查：`divide(6,3)==2` 和捕获除零异常后得到 True。",
      hint: "第二个检查可以用 try/except 得到 zero_check = True。",
      defaultCode: "# 实现 divide 并写自测 self_checks\n",
      solution: "def divide(a, b):\n    if b == 0:\n        raise ValueError(\"b cannot be zero\")\n    return a / b\n\nnormal_check = divide(6, 3) == 2\ntry:\n    divide(1, 0)\n    zero_check = False\nexcept ValueError:\n    zero_check = True\nself_checks = [normal_check, zero_check]",
      requireCode: ["raise ValueError"],
      requiredNames: ["divide", "self_checks"],
      assertCode: `assert self_checks == [True, True]`,
      failPrefix: "计算器质量检查失败：",
      success: "Level 11 通关！你已经开始用质量意识写功能。"
    }),
    makeLesson({
      id: 91,
      level: 12,
      title: "91. 综合项目：TodoApp",
      heading: "从功能函数走向应用类",
      concept: "综合项目会把数据模型、业务方法和状态管理组合起来。TodoApp 是最适合起步的完整应用之一。",
      ability: "能设计一个有添加、完成、统计能力的应用类。",
      example: "app.add(\"learn\")\napp.complete(0)",
      task: "请定义类 `TodoApp`：初始化空列表；`add(title)` 添加 `{\"title\": title, \"done\": False}`；`complete(index)` 标记完成；`summary()` 返回 `{\"total\": 总数, \"done\": 已完成数}`。创建 app，添加两个任务并完成第一个，结果存入 `todo_summary`。",
      hint: "summary 里可以用 sum(1 for item in self.todos if item['done'])。",
      defaultCode: "class TodoApp:\n    pass\n\n# 创建应用并生成 todo_summary\n",
      solution: "class TodoApp:\n    def __init__(self):\n        self.todos = []\n    def add(self, title):\n        self.todos.append({\"title\": title, \"done\": False})\n    def complete(self, index):\n        self.todos[index][\"done\"] = True\n    def summary(self):\n        done_count = sum(1 for item in self.todos if item[\"done\"])\n        return {\"total\": len(self.todos), \"done\": done_count}\n\napp = TodoApp()\napp.add(\"learn\")\napp.add(\"ship\")\napp.complete(0)\ntodo_summary = app.summary()",
      requiredNames: ["TodoApp", "todo_summary"],
      assertCode: `assert todo_summary == {"total": 2, "done": 1}`,
      failPrefix: "TodoApp 检查失败：",
      success: "通关！你完成了一个可扩展应用类的核心。"
    }),
    makeLesson({
      id: 92,
      level: 12,
      title: "92. 综合项目：记账本",
      heading: "管理收入和支出",
      concept: "记账本能练数据模型、分类汇总和余额计算，是非常实用的个人项目。",
      ability: "能实现交易记录、余额和分类统计。",
      example: "ledger.add(\"food\", -20)\nledger.balance()",
      task: "请定义类 `ExpenseTracker`：保存交易列表；`add(category, amount)` 添加记录；`balance()` 返回总金额；`total_by_category(category)` 返回某分类总金额。添加 `salary 1000`、`food -30`、`food -20`，把 food 总额存入 `food_total`，余额存入 `balance_total`。",
      hint: "交易可以保存为字典列表。",
      defaultCode: "class ExpenseTracker:\n    pass\n\n# 创建记账本并统计\n",
      solution: "class ExpenseTracker:\n    def __init__(self):\n        self.records = []\n    def add(self, category, amount):\n        self.records.append({\"category\": category, \"amount\": amount})\n    def balance(self):\n        return sum(record[\"amount\"] for record in self.records)\n    def total_by_category(self, category):\n        return sum(record[\"amount\"] for record in self.records if record[\"category\"] == category)\n\ntracker = ExpenseTracker()\ntracker.add(\"salary\", 1000)\ntracker.add(\"food\", -30)\ntracker.add(\"food\", -20)\nfood_total = tracker.total_by_category(\"food\")\nbalance_total = tracker.balance()",
      requiredNames: ["ExpenseTracker", "food_total", "balance_total"],
      assertCode: `assert food_total == -50\nassert balance_total == 950`,
      failPrefix: "记账本检查失败：",
      success: "很好！你已经能做有实际用途的个人工具核心了。"
    }),
    makeLesson({
      id: 93,
      level: 12,
      title: "93. 综合项目：单词卡片",
      heading: "做一个学习辅助工具",
      concept: "背单词工具需要保存卡片、判断答案、统计正确率。它能练类、列表和业务规则。",
      ability: "能实现卡片添加和答题判定。",
      example: "deck.add(\"cat\", \"猫\")\ndeck.check(\"cat\", \"猫\")",
      task: "请定义类 `FlashcardDeck`：`add(word, meaning)` 保存卡片；`check(word, answer)` 判断答案是否等于 meaning。添加 `python -> 蟒蛇`，把正确答案检查结果存入 `flashcard_ok`。",
      hint: "可以用字典 self.cards 保存 word 到 meaning。",
      defaultCode: "class FlashcardDeck:\n    pass\n\n# 创建卡片并检查答案\n",
      solution: "class FlashcardDeck:\n    def __init__(self):\n        self.cards = {}\n    def add(self, word, meaning):\n        self.cards[word] = meaning\n    def check(self, word, answer):\n        return self.cards.get(word) == answer\n\ndeck = FlashcardDeck()\ndeck.add(\"python\", \"蟒蛇\")\nflashcard_ok = deck.check(\"python\", \"蟒蛇\")",
      requiredNames: ["FlashcardDeck", "flashcard_ok"],
      assertCode: `assert flashcard_ok is True\nassert deck.check("python", "语言") is False`,
      failPrefix: "单词卡片检查失败：",
      success: "通关！你已经能把学习需求转成应用逻辑。"
    }),
    makeLesson({
      id: 94,
      level: 12,
      title: "94. 综合项目：笔记索引器",
      heading: "从一堆文本里建立索引",
      concept: "笔记工具、搜索工具、文档管理器都需要索引。先从标题和关键词索引开始。",
      ability: "能从笔记列表构建关键词到标题的索引。",
      example: "index.setdefault(tag, []).append(title)",
      task: "给定 `notes` 列表，每条包含 title 和 tags。请建立字典 `tag_index`，把每个 tag 映射到包含它的标题列表。",
      hint: "双层循环：遍历 notes，再遍历 note['tags']。",
      defaultCode: "notes = [{\"title\": \"Python\", \"tags\": [\"code\", \"study\"]}, {\"title\": \"Recipe\", \"tags\": [\"life\"]}, {\"title\": \"Flask\", \"tags\": [\"code\"]}]\ntag_index = {}\n# 建立标签索引\n",
      solution: "notes = [{\"title\": \"Python\", \"tags\": [\"code\", \"study\"]}, {\"title\": \"Recipe\", \"tags\": [\"life\"]}, {\"title\": \"Flask\", \"tags\": [\"code\"]}]\ntag_index = {}\nfor note in notes:\n    for tag in note[\"tags\"]:\n        tag_index.setdefault(tag, []).append(note[\"title\"])",
      requiredNames: ["tag_index"],
      assertCode: `assert tag_index["code"] == ["Python", "Flask"]\nassert tag_index["study"] == ["Python"]`,
      failPrefix: "笔记索引检查失败：",
      success: "很好！你已经能为内容工具建立基础搜索索引。"
    }),
    makeLesson({
      id: 95,
      level: 12,
      title: "95. 综合项目：日志分析器",
      heading: "从日志里发现问题",
      concept: "日志分析器是运维和后端常见工具：统计错误等级、找出异常信息、生成摘要。",
      ability: "能解析日志行并统计等级数量。",
      example: "level = line.split()[0]",
      task: "给定 `log_lines = [\"INFO start\", \"ERROR failed\", \"INFO end\", \"ERROR retry\"]`，请统计每个等级出现次数到 `log_counts`。",
      hint: "等级是每行空格前的第一个词。",
      defaultCode: "log_lines = [\"INFO start\", \"ERROR failed\", \"INFO end\", \"ERROR retry\"]\nlog_counts = {}\n# 统计日志等级\n",
      solution: "log_lines = [\"INFO start\", \"ERROR failed\", \"INFO end\", \"ERROR retry\"]\nlog_counts = {}\nfor line in log_lines:\n    level = line.split()[0]\n    log_counts[level] = log_counts.get(level, 0) + 1",
      requiredNames: ["log_counts"],
      assertCode: `assert log_counts == {"INFO": 2, "ERROR": 2}`,
      failPrefix: "日志分析检查失败：",
      success: "通关！你能把原始日志转成可读统计了。"
    }),
    makeLesson({
      id: 96,
      level: 12,
      title: "96. 综合项目：学生系统升级版",
      heading: "加入搜索和排名",
      concept: "管理系统通常需要新增、搜索、排序和导出。这个升级版继续扩展学生管理系统的能力。",
      ability: "能在管理类里实现按姓名查找和平均分排名。",
      example: "manager.find(\"Alice\")\nmanager.ranking()",
      task: "请定义 `Student` 类和 `StudentManager` 类。Student 有 name 和 scores，方法 average()。Manager 可 add(student)、find(name)、ranking()，ranking 按平均分降序返回姓名列表。添加 Alice(90)、Bob(80)，把排名存入 `student_ranking`。",
      hint: "ranking 可以用 sorted(self.students, key=lambda s: s.average(), reverse=True)。",
      defaultCode: "class Student:\n    pass\n\nclass StudentManager:\n    pass\n\n# 添加学生并生成排名\n",
      solution: "class Student:\n    def __init__(self, name, scores):\n        self.name = name\n        self.scores = scores\n    def average(self):\n        if not self.scores:\n            return 0\n        return sum(self.scores) / len(self.scores)\n\nclass StudentManager:\n    def __init__(self):\n        self.students = []\n    def add(self, student):\n        self.students.append(student)\n    def find(self, name):\n        for student in self.students:\n            if student.name == name:\n                return student\n        return None\n    def ranking(self):\n        return [student.name for student in sorted(self.students, key=lambda s: s.average(), reverse=True)]\n\nmanager = StudentManager()\nmanager.add(Student(\"Alice\", [90, 90]))\nmanager.add(Student(\"Bob\", [80, 80]))\nstudent_ranking = manager.ranking()",
      requiredNames: ["Student", "StudentManager", "student_ranking"],
      assertCode: `assert student_ranking == ["Alice", "Bob"]\nassert manager.find("Bob").average() == 80`,
      failPrefix: "学生系统升级检查失败：",
      success: "很好！你的管理系统已经具备搜索和排名能力。"
    }),
    makeLesson({
      id: 97,
      level: 12,
      title: "97. 综合项目：API 缓存客户端",
      heading: "避免重复请求",
      concept: "真实 API 可能慢或有限流。缓存客户端可以把已经获取过的数据保存起来，减少重复请求。",
      ability: "能实现带缓存的客户端类。",
      example: "if key not in cache: cache[key] = fetch(key)",
      task: "请定义类 `CachedClient`：构造时接收 `fetcher` 函数并初始化 `cache` 字典；方法 `get(key)` 如果缓存有值直接返回，否则调用 fetcher 保存后返回。使用 fake_fetcher 返回 `key.upper()`，调用两次 `get(\"a\")`，结果存入 `cached_value`。",
      hint: "缓存命中时不要再次调用 fetcher。",
      defaultCode: "# 定义 CachedClient\n",
      solution: "class CachedClient:\n    def __init__(self, fetcher):\n        self.fetcher = fetcher\n        self.cache = {}\n    def get(self, key):\n        if key not in self.cache:\n            self.cache[key] = self.fetcher(key)\n        return self.cache[key]\n\ndef fake_fetcher(key):\n    return key.upper()\n\nclient = CachedClient(fake_fetcher)\nclient.get(\"a\")\ncached_value = client.get(\"a\")",
      requiredNames: ["CachedClient", "cached_value"],
      assertCode: `assert cached_value == "A"\nassert client.cache == {"a": "A"}`,
      failPrefix: "API 缓存客户端检查失败：",
      success: "通关！你的接口工具开始考虑效率和稳定性了。"
    }),
    makeLesson({
      id: 98,
      level: 12,
      title: "98. 综合项目：静态页面生成器",
      heading: "把内容生成 HTML 文件",
      concept: "静态站点生成器会读取内容并输出 HTML。它是模板、文件写入、批处理的综合练习。",
      ability: "能把标题和正文渲染成 HTML 并写入文件。",
      example: "html = f\"<h1>{title}</h1>\"",
      task: "请定义函数 `render_page(title, body)` 返回完整 HTML 字符串，包含 `<h1>` 和 `<p>`。调用后写入 `page.html`，并把文件内容读入 `page_html`。",
      hint: "with open('page.html', 'w') 写入，再读回。",
      defaultCode: "# 定义 render_page 并写入 page.html\n",
      solution: "def render_page(title, body):\n    return f\"<html><body><h1>{title}</h1><p>{body}</p></body></html>\"\n\nhtml = render_page(\"Hello\", \"Welcome\")\nwith open(\"page.html\", \"w\", encoding=\"utf-8\") as f:\n    f.write(html)\nwith open(\"page.html\", \"r\", encoding=\"utf-8\") as f:\n    page_html = f.read()",
      requireCode: ["with open"],
      requiredNames: ["render_page", "page_html"],
      assertCode: `assert "<h1>Hello</h1>" in page_html\nassert "<p>Welcome</p>" in page_html`,
      failPrefix: "静态页面生成器检查失败：",
      success: "很好！你已经能把数据和模板变成实际文件输出。"
    }),
    makeLesson({
      id: 99,
      level: 12,
      title: "99. 项目发布清单",
      heading: "交付前做最后检查",
      concept: "独立开发不仅是写功能，还包括说明文档、依赖、测试、运行入口和示例数据。发布清单能减少遗漏。",
      ability: "能为项目生成发布前检查清单并判断是否可发布。",
      example: "ready = all(checklist.values())",
      task: "请创建字典 `release_checklist`，包含 `readme`、`requirements`、`tests`、`entrypoint` 四项且都为 True。再创建 `is_ready_to_release = all(release_checklist.values())`。",
      hint: "all 可以判断所有布尔值是否都为 True。",
      defaultCode: "# 创建发布检查清单\n",
      solution: "release_checklist = {\n    \"readme\": True,\n    \"requirements\": True,\n    \"tests\": True,\n    \"entrypoint\": True\n}\nis_ready_to_release = all(release_checklist.values())",
      requiredNames: ["release_checklist", "is_ready_to_release"],
      assertCode: `assert set(release_checklist.keys()) == {"readme", "requirements", "tests", "entrypoint"}\nassert is_ready_to_release is True`,
      failPrefix: "发布清单检查失败：",
      success: "通关！你开始具备项目交付意识了。"
    }),
    makeLesson({
      id: 100,
      level: 12,
      title: "100. 毕业挑战：个人项目规划器",
      heading: "把想法拆成可开发计划",
      concept: "独立开发的真正起点，是能把一个模糊想法拆成目标、功能、数据、接口和里程碑。最后一关不追求炫技，而是训练项目规划能力。",
      ability: "能产出一个结构化项目计划，作为真正动手开发的起点。",
      example: "project_plan = {\"goal\": \"...\", \"features\": [...]}",
      task: "请创建字典 `project_plan`，至少包含：`goal` 字符串、`features` 列表（不少于 3 项）、`data_model` 字典、`milestones` 列表（不少于 2 项）。再创建 `graduation_ready`，当 features 和 milestones 数量都达标时为 True。",
      hint: "这是毕业规划题。你可以设计任意项目，例如记账本、单词卡、博客、文件整理器。",
      defaultCode: "# 设计你的第一个独立项目计划\nproject_plan = {}\ngraduation_ready = False\n",
      solution: "project_plan = {\n    \"goal\": \"做一个个人记账工具\",\n    \"features\": [\"添加收支\", \"按分类统计\", \"导出月度报告\"],\n    \"data_model\": {\n        \"record\": [\"date\", \"category\", \"amount\", \"note\"]\n    },\n    \"milestones\": [\"完成命令行版本\", \"加入文件保存\", \"生成统计报告\"]\n}\ngraduation_ready = len(project_plan[\"features\"]) >= 3 and len(project_plan[\"milestones\"]) >= 2",
      requiredNames: ["project_plan", "graduation_ready"],
      assertCode: `assert isinstance(project_plan.get("goal"), str) and project_plan["goal"]\nassert len(project_plan.get("features", [])) >= 3\nassert isinstance(project_plan.get("data_model"), dict)\nassert len(project_plan.get("milestones", [])) >= 2\nassert graduation_ready is True`,
      failPrefix: "毕业项目规划检查失败：",
      success: "毕业通关！你已经完成从 Python 基础到独立项目规划的完整修炼路线。接下来，就真的可以选一个项目开工了。"
    })
  ];

  lessons.push(...advancedLessons);

  if (typeof window !== "undefined") {
    window.lessons = lessons;
  }
})();
